export const ADD_FILTER_FUEL_TYPE = "ADD_FILTER_FUEL_TYPE";
export const REMOVE_FILTER_FUEL_TYPE = "REMOVE_FILTER_FUEL_TYPE";
export const CHANGE_MIN_PRICE = "MIN_PRICE";
export const CHANGE_MAX_PRICE = "MAX_PRICE";
export const CLEAR_FILTERS = "CLEAR_FILTERS";
export const SORT_BY_PRICE_LOW_TO_HIGH = "SORT_BY_PRICE_LOW_TO_HIGH";
export const SORT_BY_PRICE_HIGH_TO_LOW = "SORT_BY_PRICE_HIGH_TO_LOW";
export const SORT_BY_YEAR_NEWEST = "SORT_BY_YEAR_NEWEST";

export const FETCH_PRODUCT_PENDING = "FETCH_PRODUCT_PENDING";
export const FETCH_PRODUCT_SUCCESS = "FETCH_PRODUCT_SUCCESS";
export const FETCH_PRODUCT_FAILURE = "FETCH_PRODUCT_FAILURE";
export const CAR_LIKED = "CAR_LIKED";
export const CAR_UNLIKED = "CAR_UNLIKED";